# Contiki network configuration
MAKE_NET = MAKE_NET_NULLNET

CONTIKI_PROJECT = clicker-ng
all: $(CONTIKI_PROJECT)


CONTIKI = $(HOME)/contiki-ng-wcnes
CFLAGS += -std=c99

include $(CONTIKI)/Makefile.include
